### ISSUE TITLE
Traceback (most recent call last):   File "/data/data/com.termux/files/usr/bin/E4GL30S1NT", line 21, in <module>     import pyperclip ModuleNotFoundError: No module named 'pyperclip'

### ISSUE THREAD

**Issue by Kitopvibe1** [C0MPL3XDEV/E4GL30S1NT#11]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/E4GL30S1NT", line 21, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'

![Screenshot_20220901-120433](https://user-images.githubusercontent.com/110231650/187900161-31d32495-f432-471f-8956-2faf94493cf1.jpg)

**Comment by Enn3Developer** [comment]
not the original author, just an outsider
https://pypi.org/project/pyperclip/
