### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by philmacrack** [C0MPL3XDEV/E4GL30S1NT#7]
im having trouble installing, here is my terminal : 
#
sudo ./linuxinstall.sh
> E4GL30SINT - Simple information gathering toolkit
> prepare for installing dependencies ...
> installing package: libxml2
./linuxinstall.sh: line 11: pkg: command not found
> installing pacakge: libxslt
./linuxinstall.sh: line 13: pkg: command not found
> installing pacakge: python3
./linuxinstall.sh: line 15: pkg: command not found
> installing modules: lxml
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.37.1)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (4.8.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> installing modules: requests
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.9.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> installing modules: BeautifulSoup
Collecting BeautifulSoup
  Using cached BeautifulSoup-3.2.2.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xop6l9cq/beautifulsoup_53bc2329fad14180854f52b14691a342/setup.py", line 3
          "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                         ^^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
> installing modules: tabuate
Requirement already satisfied: tabulate in /usr/lib/python3/dist-packages (0.8.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> successfully installing dependencies
> use command E4GL30S1NT for start the console

**Comment by philmacrack** [comment]
cd to root of folder "/E4GL30S1NT", then sudo python3.8 E4GL30S1NT.py wokred for me, dev plz update instructions
//wl

**Comment by C0MPL3XDEV** [comment]
Instruction Updated :)
